name: Snake Game

# Dispara a execução a cada 5 horas ou manualmente
on:
  schedule:
    # Will be updated every 5 hours
    - cron: "0 */5 * * *"
  workflow_dispatch:

jobs:
  generate-and-deploy-snake-game:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Generate Snake Game Assets
      - name: Generate Snake Game Assets
        uses: Platane/snk@master  # Consider updating to a specific version
        id: snake-gif
        with:
          github_user_name: Hudson-castro
          gif_out_path: dist/github-contribution-grid-snake.gif
          svg_out_path: dist/github-contribution-grid-snake.svg

      # 3. Check for changes 
      - name: Check for changes
        run: git status --porcelain

      # 4. Commit and Push Changes (if necessary)
      - name: Commit and Push Changes (if applicable)
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add dist/
            git commit -m "Update Snake Game assets"
            git push origin main
          else
            echo "No changes to commit."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 5. Deploy to GitHub Pages (deploy to branch 'output')
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v3.x  # Update to a newer version
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
