name: Generate GitHub Contribution Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Executa diariamente à meia-noite
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Generate GitHub contribution grid snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          palette: github-dark
        id: generate-snake

      - name: Check if snake SVG was generated
        run: |
          if [ -f dist/github-contribution-grid-snake.svg ]; then
            echo "Snake SVG generated successfully"
          else
            echo "Failed to generate snake SVG. Exiting workflow."
            exit 1
          fi

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: gh-pages
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
